language: java
cache:
  apt: true
  directories:
  - $HOME/.m2 # maven
before_script:
- psql -c 'create database wdc2;' -U postgres
- psql -f wdc2.sql -U postgres -d wdc2
env:
- MINIFY_CODE=true MERGE_JS=true
- MERGE_JS=true
- MINIFY_CODE=true
-
os:
- linux
- osx
deploy:
  provider: heroku
  api_key:
    secure: ZZa7bwqqwgk/9OzXr3GH6xjQwTydFxvAeNSvkWM8SRQUm7JiXKNaTgjuUoG3sYrjURI5oWNkDUgj+QIUk8UztA1yX2JRhntp+Co2w6fbDdaDONhVgTi69zYiMFT8pgrYrduFl/p/OY6drOz/Jh8IBZzUK5egidv+qmjEIGa3DpY=
  app: wdc-app
  on:
    repo: sochka/wdc
