language: java
cache: # only for private repos
  apt: true
  directories:
  - $HOME/.m2
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- mvn process-test-classes # don't use mvn install or default settings because of the bug in frontend-maven plugin
before_script:
- echo Starting tomcat server...
- mvn tomcat7:run &
- psql -c 'create database wdc2;' -U postgres
- psql -d wdc2 -f schema_wdc2.sql -U postgres
- psql -d wdc2 -f data_wdc2.sql -U postgres
- echo Waiting until server starts..
- sleep 120
script:
- mvn test
env:
  matrix:
  - MINIFY_CODE=true MERGE_JS=true
  - MERGE_JS=true
  - MINIFY_CODE=true
  -
  global:
  # sauce
  - secure: XQXmNe9FkpcNxWvmr+8qvvMFj6E/GAE6d7KFDAVw/LYfquSImZkqMcRqlRkDmVHh9B8N6eALFMbS7biO2cRPfRKhN5YVegrX2PUbjszWvnrLiCO1/u14d2bdGWLtP/j+wvwtNCCAtwprlNbTDDXQib9IlRSGs9ofQEvM8n6Tn5M=
  - secure: Y0u9BWagQ3uUAY8KjmJlLKHYPJBubKmapF5hNLYbKWZxQ62ylFn5SqOHplRxRbmEUeVWE4PcRhWJAG+AofNHg2ZpIuUOQnTxXDr+FDL35zHYscATGRd+UHXqKeApDTt6oqZPIQbQjqZ9CCI5n4KdFeKvI5ovil+wkMT57XMP1iA=
addons:
  sauce_connect: true
os:
- linux
- osx # temporary not available on travis
node_js:
- "0.11"
- "0.10"
deploy:
  provider: heroku
  api_key:
    secure: ZZa7bwqqwgk/9OzXr3GH6xjQwTydFxvAeNSvkWM8SRQUm7JiXKNaTgjuUoG3sYrjURI5oWNkDUgj+QIUk8UztA1yX2JRhntp+Co2w6fbDdaDONhVgTi69zYiMFT8pgrYrduFl/p/OY6drOz/Jh8IBZzUK5egidv+qmjEIGa3DpY=
  app: wdc-app
  strategy: git
  on:
    repo: sochka/wdc
