language: node_js
# use container-based environment
# which results in faster start-ups and allows caching
sudo: false
cache:
  directories:
  - node_modules
  - .tmp/bower_components
matrix:
  include:
  - node_js: '0.12'
    env: PRODUCTION=true
  - node_js: '0.12'
    env: SEND_COVERAGE=true
  - node_js: '0.10'
  - node_js: iojs

