language: java
cache:
  apt: true
  directories:
  - $HOME/.m2 # maven
before_install:
- export DISPLAY=:99.0 # for JS testing in real browser
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database wdc2;' -U postgres
- psql -d wdc2 -f schema_wdc2.sql -U postgres
- psql -d wdc2 -f data_wdc2.sql -U postgres
env:
- MINIFY_CODE=true MERGE_JS=true
- MERGE_JS=true
- MINIFY_CODE=true
-
os:
- linux
- osx
node_js:
- "0.11"
- "0.10"
deploy:
  provider: heroku
  api_key:
    secure: ZZa7bwqqwgk/9OzXr3GH6xjQwTydFxvAeNSvkWM8SRQUm7JiXKNaTgjuUoG3sYrjURI5oWNkDUgj+QIUk8UztA1yX2JRhntp+Co2w6fbDdaDONhVgTi69zYiMFT8pgrYrduFl/p/OY6drOz/Jh8IBZzUK5egidv+qmjEIGa3DpY=
  app: wdc-app
  strategy: git
  on:
    repo: sochka/wdc
