language: node_js
# use container-based environment
# which results in faster start-ups and allows caching
sudo: false
cache:
  directories:
  - $HOME/.npm
  - .tmp/bower_components
-before_script:
# start virtual X frame-buffer for testing on firefox
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
services:
- mongodb
matrix:
  include:
    - node_js: "0.12"
      env: PRODUCTION=true
    - node_js: "0.12"
      env: SEND_COVERAGE=true
    - node_js: "0.10"
    - node_js: iojs
