environment:
  nodejs_version: "0.12"
install:
- ps: Install-Product node $env:nodejs_version
- npm install
test_script:
# Output useful info for debugging.
- node --version
- npm --version
# run tests
- npm test
cache:
- .tmp\bower_components
- C:\Users\appveyor\AppData\Roaming\npm-cache
# Don't actually build.
build: off
